In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from autorank import autorank, plot_stats, create_report, latex_table

## ASVspoof 2019

In [87]:
wavelet_2019 = pd.read_csv("../results/v2.5/wavelets_results_grouped_2019.csv")
max_2019 = pd.read_csv("../results/v2.5/max_results_grouped_2019.csv")
average_2019 = pd.read_csv("../results/v2.5/average_results_grouped_2019.csv")

In [88]:
model_results_2019 = pd.concat([wavelet_2019, max_2019, average_2019])

In [89]:
autorank_input_2019 = model_results_2019.pivot(index='seed', columns='wavelet_family', values='eer')
autorank_input_2019

wavelet_family,Average,Max,db14,db16,db18,db24,db26,db28,db34,db36,db38,db4,db6,db8
seed,,,,,,,,,,,,,,
42,0.062101,0.068806,0.074591,0.076720,0.060847,0.069065,0.058192,0.062396,0.068282,0.074434,0.074825,0.059203,0.070787,0.086597
49,0.072603,0.068113,0.063086,0.065661,0.065708,0.063240,0.061333,0.069636,0.080467,0.067575,0.075886,0.065261,0.059834,0.073034
51,0.064039,0.069605,0.060367,0.067573,0.078722,0.062428,0.073148,0.058328,0.067186,0.083073,0.068525,0.060487,0.060095,0.061191
69,0.073295,0.068145,0.080060,0.069474,0.055067,0.064332,0.057512,0.075740,0.073011,0.070427,0.061033,0.067299,0.062939,0.060341
73,0.067860,0.061709,0.065715,0.070292,0.089931,0.063630,0.095173,0.072665,0.068345,0.079810,0.072164,0.070489,0.066153,0.066349

In [90]:
result_2019 = autorank(autorank_input_2019, alpha=0.05, verbose=False)
print(result_2019)

         meanrank      mean       std  ci_lower  ci_upper effect_size  \
db6          10.8  0.063962  0.004594  0.051351  0.076572         0.0
db24          9.8  0.064539  0.002622  0.057342  0.071736   -0.154284
db4           9.6  0.064548  0.004702   0.05164  0.077455   -0.126069
db26          8.8  0.069072  0.015889  0.025457  0.112686   -0.436921
db14          8.2  0.068764  0.008270  0.046061  0.091466   -0.717814
Max           7.8  0.067276  0.003170  0.058573  0.075979   -0.839604
db18          7.6  0.070055  0.014129  0.031271  0.108839   -0.580013
db8           7.2  0.069502  0.010813  0.039821  0.099184    -0.66698
Average       7.0  0.067980  0.004993  0.054273  0.081686   -0.837469
db28          7.0  0.067753  0.007228  0.047911  0.087595   -0.626028
db16          6.0  0.069944  0.004190  0.058443  0.081445   -1.360697
db34          5.8  0.071458  0.005514  0.056323  0.086593   -1.477233
db38          5.2  0.070487  0.006000  0.054016  0.086958   -1.221078
db36          4.2  0.075064  0.006415  0.057453  0.092675   -1.989793

          magnitude effect_size_above magnitude_above
db6      negligible               0.0      negligible
db24     negligible         -0.154284      negligible
db4      negligible         -0.002351      negligible
db26          small         -0.386104           small
db14         medium          0.024311      negligible
Max           large            0.2376           small
db18         medium         -0.271459           small
db8          medium          0.043924      negligible
Average       large          0.180814      negligible
db28         medium          0.036489      negligible
db16          large         -0.370864           small
db34          large         -0.309234           small
db38          large          0.168604      negligible
db36          large         -0.736897          medium
RankResult(rankdf=
         meanrank      mean       std  ci_lower  ci_upper effect_size  \
db6          10.8  0.063962  0.004594  0.051351  0.076572         0.0
db24          9.8  0.064539  0.002622  0.057342  0.071736   -0.154284
db4           9.6  0.064548  0.004702   0.05164  0.077455   -0.126069
db26          8.8  0.069072  0.015889  0.025457  0.112686   -0.436921
db14          8.2  0.068764  0.008270  0.046061  0.091466   -0.717814
Max           7.8  0.067276  0.003170  0.058573  0.075979   -0.839604
db18          7.6  0.070055  0.014129  0.031271  0.108839   -0.580013
db8           7.2  0.069502  0.010813  0.039821  0.099184    -0.66698
Average       7.0  0.067980  0.004993  0.054273  0.081686   -0.837469
db28          7.0  0.067753  0.007228  0.047911  0.087595   -0.626028
db16          6.0  0.069944  0.004190  0.058443  0.081445   -1.360697
db34          5.8  0.071458  0.005514  0.056323  0.086593   -1.477233
db38          5.2  0.070487  0.006000  0.054016  0.086958   -1.221078
db36          4.2  0.075064  0.006415  0.057453  0.092675   -1.989793

          magnitude effect_size_above magnitude_above
db6      negligible               0.0      negligible
db24     negligible         -0.154284      negligible
db4      negligible         -0.002351      negligible
db26          small         -0.386104           small
db14         medium          0.024311      negligible
Max           large            0.2376           small
db18         medium         -0.271459           small
db8          medium          0.043924      negligible
Average       large          0.180814      negligible
db28         medium          0.036489      negligible
db16          large         -0.370864           small
db34          large         -0.309234           small
db38          large          0.168604      negligible
db36          large         -0.736897          medium
pvalue=0.46382435948088707
cd=8.873198667728083
omnibus=friedman
posthoc=nemenyi
all_normal=True
pvals_shapiro=[np.float64(0.11095733564489929), np.float64(0.07339261845839887), np.float64(0.7096131179545162), np.float64(0.41684758542625905), np.float64(0.10177121908204984), np.float64(0.01888366660523359), np.float64(0.4852672173071796), np.float64(0.8003838872089307), np.float64(0.7067845536413524), np.float64(0.31846417399558935), np.float64(0.4396163578875282), np.float64(0.5300511150161816), np.float64(0.44554124488129104), np.float64(0.6993515947311337)]
homoscedastic=False
pval_homogeneity=0.012691130560703829
homogeneity_test=bartlett
alpha=0.05
alpha_normality=0.0035714285714285718
num_samples=5
posterior_matrix=
None
decision_matrix=
None
rope=None
rope_mode=None
effect_size=cohen_d
force_mode=None)

In [91]:
create_report(result_2019)

The statistical analysis was conducted for 14 populations with 5 paired samples.
The family-wise significance level of the tests is alpha=0.050.
We failed to reject the null hypothesis that the population is normal for all populations (minimal observed p-value=0.019). Therefore, we assume that all populations are normal.
We applied Bartlett's test for homogeneity and reject the null hypothesis (p=0.013) that thedata is homoscedastic. Thus, we assume that our data is heteroscedastic.
Because we have more than two populations and the populations are normal but heteroscedastic, we use the non-parametric Friedman test as omnibus test to determine if there are any significant differences between the mean values of the populations. We use the post-hoc Nemenyi test to infer which differences are significant. We report the mean value (M), the standard deviation (SD) and the mean rank (MR) among all populations over the samples. Differences between populations are significant, if the difference of the mean rank is greater than the critical distance CD=8.873 of the Nemenyi test.
We failed to reject the null hypothesis (p=0.464) of the Friedman test that there is no difference in the central tendency of the populations db6 (M=0.064+-0.013, SD=0.005, MR=10.800), db24 (M=0.065+-0.007, SD=0.003, MR=9.800), db4 (M=0.065+-0.013, SD=0.005, MR=9.600), db26 (M=0.069+-0.044, SD=0.016, MR=8.800), db14 (M=0.069+-0.023, SD=0.008, MR=8.200), Max (M=0.067+-0.009, SD=0.003, MR=7.800), db18 (M=0.070+-0.039, SD=0.014, MR=7.600), db8 (M=0.070+-0.030, SD=0.011, MR=7.200), Average (M=0.068+-0.014, SD=0.005, MR=7.000), db28 (M=0.068+-0.020, SD=0.007, MR=7.000), db16 (M=0.070+-0.012, SD=0.004, MR=6.000), db34 (M=0.071+-0.015, SD=0.006, MR=5.800), db38 (M=0.070+-0.016, SD=0.006, MR=5.200), and db36 (M=0.075+-0.018, SD=0.006, MR=4.200). Therefore, we assume that there is no statistically significant difference between the median values of the populations.

## ASVspoof 2021

In [92]:
wavelet_2021= pd.read_csv("../results/v2.5/wavelets_results_grouped_2021.csv")
max_2021 = pd.read_csv("../results/v2.5/max_results_grouped_2021.csv")
average_2021= pd.read_csv("../results/v2.5/average_results_grouped_2021.csv")

In [93]:
average_2021

         dataset       eer  seed wavelet_family
0  ASVspoof 2021  0.144482    42        Average
1  ASVspoof 2021  0.142802    51        Average
2  ASVspoof 2021  0.143346    73        Average
3  ASVspoof 2021  0.154185    69        Average
4  ASVspoof 2021  0.146332    49        Average

In [94]:
model_results_2021 = pd.concat([wavelet_2021, max_2021, average_2021])

In [95]:
autorank_input_2021 = model_results_2021.pivot(index='seed', columns='wavelet_family', values='eer')
autorank_input_2021

wavelet_family,Average,Max,db14,db16,db18,db24,db26,db28,db34,db36,db38,db4,db6,db8
seed,,,,,,,,,,,,,,
42,0.144482,0.151421,0.150827,0.171162,0.144158,0.153804,0.143616,0.149252,0.145181,0.147670,0.152458,0.148626,0.165927,0.174290
49,0.146332,0.142815,0.152016,0.142520,0.141612,0.154784,0.141123,0.145351,0.160306,0.147997,0.162697,0.141712,0.145351,0.160917
51,0.142802,0.147517,0.137871,0.146462,0.149523,0.142189,0.159992,0.153635,0.174561,0.193421,0.142803,0.152883,0.152636,0.140276
69,0.154185,0.150239,0.148331,0.148435,0.143507,0.144437,0.141074,0.151801,0.158031,0.156731,0.143073,0.143893,0.149422,0.141666
73,0.143346,0.149310,0.152233,0.151041,0.169489,0.141000,0.162414,0.159968,0.150845,0.147670,0.149693,0.142771,0.143291,0.143654

In [96]:
result_2021 = autorank(autorank_input_2021, alpha=0.05, verbose=False)
print(result_2021)

         meanrank      mean       std  ci_lower  ci_upper effect_size  \
db4           9.8  0.145977  0.004678  0.133137  0.158817         0.0
db26          9.4  0.149644  0.010637  0.120446  0.178842   -0.446257
db18          9.0  0.149658  0.011469  0.118176  0.181139   -0.420255
Average       8.8  0.146230  0.004648  0.133471  0.158988   -0.054184
db24          8.6  0.147243  0.006563  0.129226  0.165259   -0.222071
db8           7.8  0.152161  0.014917  0.111212  0.193109   -0.559372
db14          7.6  0.148256  0.006009  0.131762  0.164749   -0.423187
Max           7.4  0.148260  0.003362  0.139032  0.157489   -0.560519
db6           7.1  0.151325  0.008927   0.12682  0.175831   -0.750446
db38          7.0  0.150145  0.008171  0.127716  0.172573   -0.626024
db16          6.8  0.151924  0.011195  0.121192  0.182655   -0.693133
db36          5.6  0.158698  0.019795  0.104361  0.213034   -0.884455
db28          5.5  0.152001  0.005430  0.137095  0.166908   -1.188669
db34          4.6  0.157785  0.011123  0.127252  0.188318   -1.383895

          magnitude effect_size_above magnitude_above
db4      negligible               0.0      negligible
db26          small         -0.446257           small
db18          small         -0.001262      negligible
Average  negligible          0.391761           small
db24          small         -0.178119      negligible
db8          medium         -0.426764           small
db14          small          0.343398           small
Max          medium         -0.000935      negligible
db6          medium         -0.454384           small
db38         medium          0.137957      negligible
db16         medium         -0.181538      negligible
db36          large         -0.421243           small
db28          large           0.46137           small
db34          large         -0.660802          medium
RankResult(rankdf=
         meanrank      mean       std  ci_lower  ci_upper effect_size  \
db4           9.8  0.145977  0.004678  0.133137  0.158817         0.0
db26          9.4  0.149644  0.010637  0.120446  0.178842   -0.446257
db18          9.0  0.149658  0.011469  0.118176  0.181139   -0.420255
Average       8.8  0.146230  0.004648  0.133471  0.158988   -0.054184
db24          8.6  0.147243  0.006563  0.129226  0.165259   -0.222071
db8           7.8  0.152161  0.014917  0.111212  0.193109   -0.559372
db14          7.6  0.148256  0.006009  0.131762  0.164749   -0.423187
Max           7.4  0.148260  0.003362  0.139032  0.157489   -0.560519
db6           7.1  0.151325  0.008927   0.12682  0.175831   -0.750446
db38          7.0  0.150145  0.008171  0.127716  0.172573   -0.626024
db16          6.8  0.151924  0.011195  0.121192  0.182655   -0.693133
db36          5.6  0.158698  0.019795  0.104361  0.213034   -0.884455
db28          5.5  0.152001  0.005430  0.137095  0.166908   -1.188669
db34          4.6  0.157785  0.011123  0.127252  0.188318   -1.383895

          magnitude effect_size_above magnitude_above
db4      negligible               0.0      negligible
db26          small         -0.446257           small
db18          small         -0.001262      negligible
Average  negligible          0.391761           small
db24          small         -0.178119      negligible
db8          medium         -0.426764           small
db14          small          0.343398           small
Max          medium         -0.000935      negligible
db6          medium         -0.454384           small
db38         medium          0.137957      negligible
db16         medium         -0.181538      negligible
db36          large         -0.421243           small
db28          large           0.46137           small
db34          large         -0.660802          medium
pvalue=0.7816540400787847
cd=8.873198667728083
omnibus=friedman
posthoc=nemenyi
all_normal=True
pvals_shapiro=[np.float64(0.09614908824187923), np.float64(0.9540124626137271), np.float64(0.05072787713693404), np.float64(0.40039781864633806), np.float64(0.03237246618651429), np.float64(0.03583289220678062), np.float64(0.4067438782112759), np.float64(0.33579166460181525), np.float64(0.15011308977136106), np.float64(0.3695908539293403), np.float64(0.005540018967758447), np.float64(0.0731081363765254), np.float64(0.8167954497772534), np.float64(0.1411020190302552)]
homoscedastic=False
pval_homogeneity=0.04833946523596061
homogeneity_test=bartlett
alpha=0.05
alpha_normality=0.0035714285714285718
num_samples=5
posterior_matrix=
None
decision_matrix=
None
rope=None
rope_mode=None
effect_size=cohen_d
force_mode=None)

In [97]:
create_report(result_2021)

The statistical analysis was conducted for 14 populations with 5 paired samples.
The family-wise significance level of the tests is alpha=0.050.
We failed to reject the null hypothesis that the population is normal for all populations (minimal observed p-value=0.006). Therefore, we assume that all populations are normal.
We applied Bartlett's test for homogeneity and reject the null hypothesis (p=0.048) that thedata is homoscedastic. Thus, we assume that our data is heteroscedastic.
Because we have more than two populations and the populations are normal but heteroscedastic, we use the non-parametric Friedman test as omnibus test to determine if there are any significant differences between the mean values of the populations. We use the post-hoc Nemenyi test to infer which differences are significant. We report the mean value (M), the standard deviation (SD) and the mean rank (MR) among all populations over the samples. Differences between populations are significant, if the difference of the mean rank is greater than the critical distance CD=8.873 of the Nemenyi test.
We failed to reject the null hypothesis (p=0.782) of the Friedman test that there is no difference in the central tendency of the populations db4 (M=0.146+-0.013, SD=0.005, MR=9.800), db26 (M=0.150+-0.029, SD=0.011, MR=9.400), db18 (M=0.150+-0.031, SD=0.011, MR=9.000), Average (M=0.146+-0.013, SD=0.005, MR=8.800), db24 (M=0.147+-0.018, SD=0.007, MR=8.600), db8 (M=0.152+-0.041, SD=0.015, MR=7.800), db14 (M=0.148+-0.016, SD=0.006, MR=7.600), Max (M=0.148+-0.009, SD=0.003, MR=7.400), db6 (M=0.151+-0.025, SD=0.009, MR=7.100), db38 (M=0.150+-0.022, SD=0.008, MR=7.000), db16 (M=0.152+-0.031, SD=0.011, MR=6.800), db36 (M=0.159+-0.054, SD=0.020, MR=5.600), db28 (M=0.152+-0.015, SD=0.005, MR=5.500), and db34 (M=0.158+-0.031, SD=0.011, MR=4.600). Therefore, we assume that there is no statistically significant difference between the median values of the populations.