In [150]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from autorank import autorank, plot_stats, create_report, latex_table

from scipy import stats
import scikit_posthocs as sp

In [101]:
wavelet_2019 = pd.read_csv("../results/v2.5/wavelets_results_grouped_2019.csv")
max_2019 = pd.read_csv("../results/v2.5/max_results_grouped_2019.csv")
average_2019 = pd.read_csv("../results/v2.5/average_results_grouped_2019.csv")

In [102]:
model_results_2019 = pd.concat([wavelet_2019, max_2019, average_2019])

In [103]:
autorank_input_2019 = model_results_2019.pivot(index='seed', columns='wavelet_family', values='eer')
autorank_input_2019

wavelet_family,Average,Max,db14,db16,db18,db24,db26,db28,db34,db36,db38,db4,db6,db8
seed,,,,,,,,,,,,,,
42,0.062101,0.068806,0.074591,0.076720,0.060847,0.069065,0.058192,0.062396,0.068282,0.074434,0.074825,0.059203,0.070787,0.086597
49,0.072603,0.068113,0.070289,0.081052,0.067983,0.075325,0.073525,0.070158,0.062540,0.054522,0.079807,0.072480,0.065961,0.061856
51,0.064039,0.069605,0.060367,0.067573,0.078722,0.062428,0.073148,0.058328,0.067186,0.083073,0.068525,0.060487,0.060095,0.061191
69,0.073295,0.068145,0.080060,0.069474,0.055067,0.064332,0.057512,0.075740,0.073011,0.070427,0.061033,0.067299,0.062939,0.060341
73,0.067860,0.061709,0.065715,0.070292,0.089931,0.063630,0.095173,0.072665,0.068345,0.079810,0.072164,0.070489,0.066153,0.066349

In [107]:
wavelet_2021= pd.read_csv("../results/v2.5/wavelets_results_grouped_2021.csv")
max_2021 = pd.read_csv("../results/v2.5/max_results_grouped_2021.csv")
average_2021= pd.read_csv("../results/v2.5/average_results_grouped_2021.csv")

In [109]:
model_results_2021 = pd.concat([wavelet_2021, max_2021, average_2021])

In [110]:
autorank_input_2021 = model_results_2021.pivot(index='seed', columns='wavelet_family', values='eer')
autorank_input_2021

wavelet_family,Average,Max,db14,db16,db18,db24,db26,db28,db34,db36,db38,db4,db6,db8
seed,,,,,,,,,,,,,,
42,0.144482,0.151421,0.150827,0.171162,0.144158,0.153804,0.143616,0.149252,0.145181,0.147670,0.152458,0.148626,0.165927,0.174290
49,0.146332,0.142815,0.151366,0.159492,0.156950,0.150336,0.150127,0.150172,0.143890,0.143292,0.167354,0.160689,0.145132,0.166051
51,0.142802,0.147517,0.137871,0.146462,0.149523,0.142189,0.159992,0.153635,0.174561,0.193421,0.142803,0.152883,0.152636,0.140276
69,0.154185,0.150239,0.148331,0.148435,0.143507,0.144437,0.141074,0.151801,0.158031,0.156731,0.143073,0.143893,0.149422,0.141666
73,0.143346,0.149310,0.152233,0.151041,0.169489,0.141000,0.162414,0.159968,0.150845,0.147670,0.149693,0.142771,0.143291,0.143654

## AutoRank

### ASVspoof 2019

In [104]:
result_2019 = autorank(autorank_input_2019, alpha=0.05, verbose=False)
print(result_2019)

         meanrank      mean       std  ci_lower  ci_upper effect_size  \
db6          10.2  0.065187  0.003996  0.054218  0.076156         0.0
db8           9.2  0.067267  0.011053  0.036926  0.097607    -0.25023
db4           8.8  0.065992  0.005925  0.049727  0.082256   -0.159169
Max           8.4  0.067276  0.003170  0.058573  0.075979   -0.579002
db24          8.2  0.066956  0.005314   0.05237  0.081542   -0.376203
db18          8.0  0.070510  0.013990  0.032108  0.108913   -0.517387
db34          8.0  0.067873  0.003732  0.057629  0.078116   -0.694663
db28          7.6  0.067858  0.007266  0.047912  0.087803   -0.455411
Average       7.2  0.067980  0.004993  0.054273  0.081686    -0.61752
db14          7.2  0.070204  0.007637   0.04924  0.091168   -0.823184
db26          7.0  0.071510  0.015330  0.029429  0.113591   -0.564433
db36          5.6  0.072453  0.011141  0.041872  0.103035   -0.868188
db38          5.2  0.071271  0.007047  0.051926  0.090615   -1.062006
db16          4.4  0.073022  0.005654  0.057501  0.088544   -1.600357

          magnitude effect_size_above magnitude_above
db6      negligible               0.0      negligible
db8           small          -0.25023           small
db4      negligible          0.143804      negligible
Max          medium         -0.270215           small
db24          small          0.073092      negligible
db18         medium         -0.335884           small
db34         medium          0.257594           small
db28          small          0.002636      negligible
Average      medium         -0.019602      negligible
db14          large         -0.344788           small
db26         medium         -0.107811      negligible
db36          large         -0.070384      negligible
db38          large           0.12684      negligible
db16          large         -0.274153           small
RankResult(rankdf=
         meanrank      mean       std  ci_lower  ci_upper effect_size  \
db6          10.2  0.065187  0.003996  0.054218  0.076156         0.0
db8           9.2  0.067267  0.011053  0.036926  0.097607    -0.25023
db4           8.8  0.065992  0.005925  0.049727  0.082256   -0.159169
Max           8.4  0.067276  0.003170  0.058573  0.075979   -0.579002
db24          8.2  0.066956  0.005314   0.05237  0.081542   -0.376203
db18          8.0  0.070510  0.013990  0.032108  0.108913   -0.517387
db34          8.0  0.067873  0.003732  0.057629  0.078116   -0.694663
db28          7.6  0.067858  0.007266  0.047912  0.087803   -0.455411
Average       7.2  0.067980  0.004993  0.054273  0.081686    -0.61752
db14          7.2  0.070204  0.007637   0.04924  0.091168   -0.823184
db26          7.0  0.071510  0.015330  0.029429  0.113591   -0.564433
db36          5.6  0.072453  0.011141  0.041872  0.103035   -0.868188
db38          5.2  0.071271  0.007047  0.051926  0.090615   -1.062006
db16          4.4  0.073022  0.005654  0.057501  0.088544   -1.600357

          magnitude effect_size_above magnitude_above
db6      negligible               0.0      negligible
db8           small          -0.25023           small
db4      negligible          0.143804      negligible
Max          medium         -0.270215           small
db24          small          0.073092      negligible
db18         medium         -0.335884           small
db34         medium          0.257594           small
db28          small          0.002636      negligible
Average      medium         -0.019602      negligible
db14          large         -0.344788           small
db26         medium         -0.107811      negligible
db36          large         -0.070384      negligible
db38          large           0.12684      negligible
db16          large         -0.274153           small
pvalue=0.7483687853266996
cd=8.873198667728083
omnibus=friedman
posthoc=nemenyi
all_normal=True
pvals_shapiro=[np.float64(0.6715513704765748), np.float64(0.3909108306173573), np.float64(0.46019827304607686), np.float64(0.013748351163878302), np.float64(0.24659423894950888), np.float64(0.8425746422128348), np.float64(0.9658392009904035), np.float64(0.6303254117124161), np.float64(0.30127327661462844), np.float64(0.4069179130695199), np.float64(0.8919549321276716), np.float64(0.9924120182159946), np.float64(0.44554124488129104), np.float64(0.01888366660523359)]
homoscedastic=False
pval_homogeneity=0.04740280423658011
homogeneity_test=bartlett
alpha=0.05
alpha_normality=0.0035714285714285718
num_samples=5
posterior_matrix=
None
decision_matrix=
None
rope=None
rope_mode=None
effect_size=cohen_d
force_mode=None)

In [105]:
create_report(result_2019)

The statistical analysis was conducted for 14 populations with 5 paired samples.
The family-wise significance level of the tests is alpha=0.050.
We failed to reject the null hypothesis that the population is normal for all populations (minimal observed p-value=0.014). Therefore, we assume that all populations are normal.
We applied Bartlett's test for homogeneity and reject the null hypothesis (p=0.047) that thedata is homoscedastic. Thus, we assume that our data is heteroscedastic.
Because we have more than two populations and the populations are normal but heteroscedastic, we use the non-parametric Friedman test as omnibus test to determine if there are any significant differences between the mean values of the populations. We use the post-hoc Nemenyi test to infer which differences are significant. We report the mean value (M), the standard deviation (SD) and the mean rank (MR) among all populations over the samples. Differences between populations are significant, if the difference of the mean rank is greater than the critical distance CD=8.873 of the Nemenyi test.
We failed to reject the null hypothesis (p=0.748) of the Friedman test that there is no difference in the central tendency of the populations db6 (M=0.065+-0.011, SD=0.004, MR=10.200), db8 (M=0.067+-0.030, SD=0.011, MR=9.200), db4 (M=0.066+-0.016, SD=0.006, MR=8.800), Max (M=0.067+-0.009, SD=0.003, MR=8.400), db24 (M=0.067+-0.015, SD=0.005, MR=8.200), db18 (M=0.071+-0.038, SD=0.014, MR=8.000), db34 (M=0.068+-0.010, SD=0.004, MR=8.000), db28 (M=0.068+-0.020, SD=0.007, MR=7.600), Average (M=0.068+-0.014, SD=0.005, MR=7.200), db14 (M=0.070+-0.021, SD=0.008, MR=7.200), db26 (M=0.072+-0.042, SD=0.015, MR=7.000), db36 (M=0.072+-0.031, SD=0.011, MR=5.600), db38 (M=0.071+-0.019, SD=0.007, MR=5.200), and db16 (M=0.073+-0.016, SD=0.006, MR=4.400). Therefore, we assume that there is no statistically significant difference between the median values of the populations.

In [106]:
latex_table(result_2019)

\begin{table}[h]
\centering
\begin{tabular}{lrrrl}
\toprule
 & MR & M & SD & CI \\
\midrule
db6 & 10.200 & 0.065 & 0.004 & [0.054, 0.076] \\
db8 & 9.200 & 0.067 & 0.011 & [0.037, 0.098] \\
db4 & 8.800 & 0.066 & 0.006 & [0.050, 0.082] \\
Max & 8.400 & 0.067 & 0.003 & [0.059, 0.076] \\
db24 & 8.200 & 0.067 & 0.005 & [0.052, 0.082] \\
db18 & 8.000 & 0.071 & 0.014 & [0.032, 0.109] \\
db34 & 8.000 & 0.068 & 0.004 & [0.058, 0.078] \\
db28 & 7.600 & 0.068 & 0.007 & [0.048, 0.088] \\
Average & 7.200 & 0.068 & 0.005 & [0.054, 0.082] \\
db14 & 7.200 & 0.070 & 0.008 & [0.049, 0.091] \\
db26 & 7.000 & 0.072 & 0.015 & [0.029, 0.114] \\
db36 & 5.600 & 0.072 & 0.011 & [0.042, 0.103] \\
db38 & 5.200 & 0.071 & 0.007 & [0.052, 0.091] \\
db16 & 4.400 & 0.073 & 0.006 & [0.058, 0.089] \\
\bottomrule
\end{tabular}
\caption{Summary of populations}
\label{tbl:stat_results}
\end{table}

### ASVspoof 2021

In [111]:
result_2021 = autorank(autorank_input_2021, alpha=0.05, verbose=False)
print(result_2021)

         meanrank      mean       std  ci_lower  ci_upper effect_size  \
Average       9.4  0.146230  0.004648  0.133471  0.158988         0.0
db24          9.2  0.146353  0.005501  0.131252  0.161455   -0.024245
db26          8.4  0.151445  0.009539   0.12526  0.177629   -0.695018
Max           8.2  0.148260  0.003362  0.139032  0.157489   -0.500589
db4           8.0  0.149773  0.007310  0.129706  0.169839   -0.578385
db14          7.8  0.148126  0.005913  0.131894  0.164357   -0.356494
db8           7.8  0.153188  0.015820  0.109761  0.196614   -0.596753
db6           7.6  0.151282  0.008964  0.126674  0.175889   -0.707514
db18          7.4  0.152725  0.010811   0.12305  0.182401    -0.78063
db36          7.0  0.157757  0.020529  0.101405  0.214108   -0.774472
db38          7.0  0.151076  0.010016  0.123581  0.178571   -0.620698
db34          6.4  0.154502  0.012527  0.120115  0.188888   -0.875527
db16          5.4  0.155318  0.010156   0.12744  0.183197   -1.150787
db28          5.4  0.152966  0.004255  0.141285  0.164646   -1.511634

          magnitude effect_size_above magnitude_above
Average  negligible               0.0      negligible
db24     negligible         -0.024245      negligible
db26         medium         -0.653877          medium
Max          medium          0.445251           small
db4          medium         -0.265809           small
db14          small          0.247711           small
db8          medium         -0.423851           small
db6          medium          0.148238      negligible
db18         medium         -0.145389      negligible
db36         medium         -0.306673           small
db38         medium          0.413605           small
db34          large         -0.302041           small
db16          large         -0.071621      negligible
db28          large          0.302178           small
RankResult(rankdf=
         meanrank      mean       std  ci_lower  ci_upper effect_size  \
Average       9.4  0.146230  0.004648  0.133471  0.158988         0.0
db24          9.2  0.146353  0.005501  0.131252  0.161455   -0.024245
db26          8.4  0.151445  0.009539   0.12526  0.177629   -0.695018
Max           8.2  0.148260  0.003362  0.139032  0.157489   -0.500589
db4           8.0  0.149773  0.007310  0.129706  0.169839   -0.578385
db14          7.8  0.148126  0.005913  0.131894  0.164357   -0.356494
db8           7.8  0.153188  0.015820  0.109761  0.196614   -0.596753
db6           7.6  0.151282  0.008964  0.126674  0.175889   -0.707514
db18          7.4  0.152725  0.010811   0.12305  0.182401    -0.78063
db36          7.0  0.157757  0.020529  0.101405  0.214108   -0.774472
db38          7.0  0.151076  0.010016  0.123581  0.178571   -0.620698
db34          6.4  0.154502  0.012527  0.120115  0.188888   -0.875527
db16          5.4  0.155318  0.010156   0.12744  0.183197   -1.150787
db28          5.4  0.152966  0.004255  0.141285  0.164646   -1.511634

          magnitude effect_size_above magnitude_above
Average  negligible               0.0      negligible
db24     negligible         -0.024245      negligible
db26         medium         -0.653877          medium
Max          medium          0.445251           small
db4          medium         -0.265809           small
db14          small          0.247711           small
db8          medium         -0.423851           small
db6          medium          0.148238      negligible
db18         medium         -0.145389      negligible
db36         medium         -0.306673           small
db38         medium          0.413605           small
db34          large         -0.302041           small
db16          large         -0.071621      negligible
db28          large          0.302178           small
pvalue=0.9662357399283029
cd=8.873198667728083
omnibus=friedman
posthoc=nemenyi
all_normal=True
pvals_shapiro=[np.float64(0.0731081363765254), np.float64(0.32267733187343545), np.float64(0.4481702396036217), np.float64(0.32731350905851375), np.float64(0.30399065411413595), np.float64(0.4067438782112759), np.float64(0.0332704709692753), np.float64(0.09916442944804243), np.float64(0.5781594074087453), np.float64(0.028402406805601462), np.float64(0.23011800806527888), np.float64(0.33908275555754036), np.float64(0.2843901781743969), np.float64(0.43065042952440713)]
homoscedastic=False
pval_homogeneity=0.032970258244848824
homogeneity_test=bartlett
alpha=0.05
alpha_normality=0.0035714285714285718
num_samples=5
posterior_matrix=
None
decision_matrix=
None
rope=None
rope_mode=None
effect_size=cohen_d
force_mode=None)

In [112]:
create_report(result_2021)

The statistical analysis was conducted for 14 populations with 5 paired samples.
The family-wise significance level of the tests is alpha=0.050.
We failed to reject the null hypothesis that the population is normal for all populations (minimal observed p-value=0.028). Therefore, we assume that all populations are normal.
We applied Bartlett's test for homogeneity and reject the null hypothesis (p=0.033) that thedata is homoscedastic. Thus, we assume that our data is heteroscedastic.
Because we have more than two populations and the populations are normal but heteroscedastic, we use the non-parametric Friedman test as omnibus test to determine if there are any significant differences between the mean values of the populations. We use the post-hoc Nemenyi test to infer which differences are significant. We report the mean value (M), the standard deviation (SD) and the mean rank (MR) among all populations over the samples. Differences between populations are significant, if the difference of the mean rank is greater than the critical distance CD=8.873 of the Nemenyi test.
We failed to reject the null hypothesis (p=0.966) of the Friedman test that there is no difference in the central tendency of the populations Average (M=0.146+-0.013, SD=0.005, MR=9.400), db24 (M=0.146+-0.015, SD=0.006, MR=9.200), db26 (M=0.151+-0.026, SD=0.010, MR=8.400), Max (M=0.148+-0.009, SD=0.003, MR=8.200), db4 (M=0.150+-0.020, SD=0.007, MR=8.000), db14 (M=0.148+-0.016, SD=0.006, MR=7.800), db8 (M=0.153+-0.043, SD=0.016, MR=7.800), db6 (M=0.151+-0.025, SD=0.009, MR=7.600), db18 (M=0.153+-0.030, SD=0.011, MR=7.400), db36 (M=0.158+-0.056, SD=0.021, MR=7.000), db38 (M=0.151+-0.027, SD=0.010, MR=7.000), db34 (M=0.155+-0.034, SD=0.013, MR=6.400), db16 (M=0.155+-0.028, SD=0.010, MR=5.400), and db28 (M=0.153+-0.012, SD=0.004, MR=5.400). Therefore, we assume that there is no statistically significant difference between the median values of the populations.

In [113]:
latex_table(result_2021)

\begin{table}[h]
\centering
\begin{tabular}{lrrrl}
\toprule
 & MR & M & SD & CI \\
\midrule
Average & 9.400 & 0.146 & 0.005 & [0.133, 0.159] \\
db24 & 9.200 & 0.146 & 0.006 & [0.131, 0.161] \\
db26 & 8.400 & 0.151 & 0.010 & [0.125, 0.178] \\
Max & 8.200 & 0.148 & 0.003 & [0.139, 0.157] \\
db4 & 8.000 & 0.150 & 0.007 & [0.130, 0.170] \\
db14 & 7.800 & 0.148 & 0.006 & [0.132, 0.164] \\
db8 & 7.800 & 0.153 & 0.016 & [0.110, 0.197] \\
db6 & 7.600 & 0.151 & 0.009 & [0.127, 0.176] \\
db18 & 7.400 & 0.153 & 0.011 & [0.123, 0.182] \\
db36 & 7.000 & 0.158 & 0.021 & [0.101, 0.214] \\
db38 & 7.000 & 0.151 & 0.010 & [0.124, 0.179] \\
db34 & 6.400 & 0.155 & 0.013 & [0.120, 0.189] \\
db16 & 5.400 & 0.155 & 0.010 & [0.127, 0.183] \\
db28 & 5.400 & 0.153 & 0.004 & [0.141, 0.165] \\
\bottomrule
\end{tabular}
\caption{Summary of populations}
\label{tbl:stat_results}
\end{table}

## Friedman Test

### ASVspoof 2019

In [145]:
average_2019 = autorank_input_2019["Average"]
max_2019 = autorank_input_2019["Max"]
db4_2019 = autorank_input_2019["db4"]
db6_2019 = autorank_input_2019["db6"]
db8_2019 = autorank_input_2019["db8"]
db14_2019 = autorank_input_2019["db14"]
db16_2019 = autorank_input_2019["db16"]
db18_2019 = autorank_input_2019["db18"]
db24_2019 = autorank_input_2019["db24"]
db26_2019 = autorank_input_2019["db26"]
db28_2019 = autorank_input_2019["db28"]
db34_2019 = autorank_input_2019["db34"]
db36_2019 = autorank_input_2019["db36"]
db38_2019 = autorank_input_2019["db38"]

In [151]:
friedman_2019 = stats.friedmanchisquare(
    average_2019, max_2019, db4_2019, db6_2019, db8_2019, db14_2019, db16_2019, db18_2019,
    db24_2019, db26_2019, db28_2019, db34_2019, db36_2019, db38_2019,
)
friedman_2019

FriedmanchisquareResult(statistic=np.float64(9.319999999999993), pvalue=np.float64(0.7483687853266996))

### ASVspoof 2021

In [147]:
average_2021 = autorank_input_2021["Average"]
max_2021 = autorank_input_2021["Max"]
db4_2021 = autorank_input_2021["db4"]
db6_2021 = autorank_input_2021["db6"]
db8_2021 = autorank_input_2021["db8"]
db14_2021 = autorank_input_2021["db14"]
db16_2021 = autorank_input_2021["db16"]
db18_2021 = autorank_input_2021["db18"]
db24_2021 = autorank_input_2021["db24"]
db26_2021 = autorank_input_2021["db26"]
db28_2021 = autorank_input_2021["db28"]
db34_2021 = autorank_input_2021["db34"]
db36_2021 = autorank_input_2021["db36"]
db38_2021 = autorank_input_2021["db38"]

In [152]:
friedman_2021 = stats.friedmanchisquare(
    average_2021, max_2021, db4_2021, db6_2021, db8_2021, db14_2021, db16_2021, db18_2021,
    db24_2021, db26_2021, db28_2021, db34_2021, db36_2021, db38_2021,
)
friedman_2021

FriedmanchisquareResult(statistic=np.float64(5.36571428571429), pvalue=np.float64(0.9662357399283029))

## Nemenyi Test

### ASVspoof 2019

In [153]:
data_2019 = np.array([average_2019, max_2019, db4_2019, db6_2019, db8_2019, db14_2019, db16_2019, db18_2019,
    db24_2019, db26_2019, db28_2019, db34_2019, db36_2019, db38_2019])

In [154]:
sp.posthoc_nemenyi_friedman(data_2019.T)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.000000,1.000000,0.999998,0.997559,0.999971,1.000000,0.998796,1.000000,1.000000,1.000000,1.000000,1.000000,0.999998,0.999971
1,1.000000,1.000000,1.000000,0.999992,1.000000,1.000000,0.965856,1.000000,1.000000,1.000000,1.000000,1.000000,0.998796,0.995378
2,0.999998,1.000000,1.000000,1.000000,1.000000,0.999998,0.928716,1.000000,1.000000,0.999992,1.000000,1.000000,0.995378,0.986122
3,0.997559,0.999992,1.000000,1.000000,1.000000,0.997559,0.635386,0.999914,0.999971,0.995378,0.999451,0.999914,0.902304,0.832516
4,0.999971,1.000000,1.000000,1.000000,1.000000,0.999971,0.870233,1.000000,1.000000,0.999914,0.999998,1.000000,0.986122,0.965856
5,1.000000,1.000000,0.999998,0.997559,0.999971,1.000000,0.998796,1.000000,1.000000,1.000000,1.000000,1.000000,0.999998,0.999971
6,0.998796,0.965856,0.928716,0.635386,0.870233,0.998796,1.000000,0.986122,0.977737,0.999451,0.995378,0.986122,1.000000,1.000000
7,1.000000,1.000000,1.000000,0.999914,1.000000,1.000000,0.986122,1.000000,1.000000,1.000000,1.000000,1.000000,0.999771,0.998796
8,1.000000,1.000000,1.000000,0.999971,1.000000,1.000000,0.977737,1.000000,1.000000,1.000000,1.000000,1.000000,0.999451,0.997559
9,1.000000,1.000000,0.999992,0.995378,0.999914,1.000000,0.999451,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.999992
10,1.000000,1.000000,1.000000,0.999451,0.999998,1.000000,0.995378,1.000000,1.000000,1.000000,1.000000,1.000000,0.999971,0.999771
11,1.000000,1.000000,1.000000,0.999914,1.000000,1.000000,0.986122,1.000000,1.000000,1.000000,1.000000,1.000000,0.999771,0.998796
12,0.999998,0.998796,0.995378,0.902304,0.986122,0.999998,1.000000,0.999771,0.999451,1.000000,0.999971,0.999771,1.000000,1.000000
13,0.999971,0.995378,0.986122,0.832516,0.965856,0.999971,1.000000,0.998796,0.997559,0.999992,0.999771,0.998796,1.000000,1.000000

### ASVspoof 2021

In [155]:
data_2021 = np.array([average_2021, max_2021, db4_2021, db6_2021, db8_2021, db14_2021, db16_2021, db18_2021,
    db24_2021, db26_2021, db28_2021, db34_2021, db36_2021, db38_2021])

In [156]:
sp.posthoc_nemenyi_friedman(data_2021.T)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.000000,1.000000,1.000000,0.999992,0.999998,0.999998,0.965856,0.999971,1.000000,1.000000,0.965856,0.997559,0.999771,0.999771
1,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.998796,1.000000,1.000000,1.000000,0.998796,0.999992,1.000000,1.000000
2,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.999451,1.000000,1.000000,1.000000,0.999451,0.999998,1.000000,1.000000
3,0.999992,1.000000,1.000000,1.000000,1.000000,1.000000,0.999914,1.000000,0.999998,1.000000,0.999914,1.000000,1.000000,1.000000
4,0.999998,1.000000,1.000000,1.000000,1.000000,1.000000,0.999771,1.000000,1.000000,1.000000,0.999771,1.000000,1.000000,1.000000
5,0.999998,1.000000,1.000000,1.000000,1.000000,1.000000,0.999771,1.000000,1.000000,1.000000,0.999771,1.000000,1.000000,1.000000
6,0.965856,0.998796,0.999451,0.999914,0.999771,0.999771,1.000000,0.999971,0.977737,0.997559,1.000000,1.000000,0.999998,0.999998
7,0.999971,1.000000,1.000000,1.000000,1.000000,1.000000,0.999971,1.000000,0.999992,1.000000,0.999971,1.000000,1.000000,1.000000
8,1.000000,1.000000,1.000000,0.999998,1.000000,1.000000,0.977737,0.999992,1.000000,1.000000,0.977737,0.998796,0.999914,0.999914
9,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.997559,1.000000,1.000000,1.000000,0.997559,0.999971,1.000000,1.000000
10,0.965856,0.998796,0.999451,0.999914,0.999771,0.999771,1.000000,0.999971,0.977737,0.997559,1.000000,1.000000,0.999998,0.999998
11,0.997559,0.999992,0.999998,1.000000,1.000000,1.000000,1.000000,1.000000,0.998796,0.999971,1.000000,1.000000,1.000000,1.000000
12,0.999771,1.000000,1.000000,1.000000,1.000000,1.000000,0.999998,1.000000,0.999914,1.000000,0.999998,1.000000,1.000000,1.000000
13,0.999771,1.000000,1.000000,1.000000,1.000000,1.000000,0.999998,1.000000,0.999914,1.000000,0.999998,1.000000,1.000000,1.000000